### ISSUE TITLE
[command-line] how can we terminate the esbmc-ai

### ISSUE THREAD

**Issue by lucasccordeiro** [Yiannis128/esbmc-ai#10]
I have tried to use the keywords exit and quit, but I didn't manage to terminate esbmc-ai. I had to use CTRL+C.

```
>: exit

assistant: OK, feel free to ask any questions if you need further assistance in the future. Goodbye!

>: quit

assistant: OK, goodbye!

>: quit

assistant: Goodbye!

>: ^CTraceback (most recent call last):
  File "/home/lucas/esbmc-ai/./main.py", line 247, in <module>
    main()
  File "/home/lucas/esbmc-ai/./main.py", line 227, in main
    user_message = i
```

**Comment by Yiannis128** [comment]
Hi, in order to start a chat command use "/'. So, in order to exit, you can use `/exit`. In order to view the help message you can use `/help`.

I think it would be a good idea to display this information as soon as the user is able to type, in order to make them aware of the actions.

**Comment by Yiannis128** [comment]
Hi, I have added a help message as soon as you start ESBMC-AI. Let me know if this is a good solution!

![image](https://user-images.githubusercontent.com/9535618/235545006-53a7a348-c4be-48ed-9f53-c39c3c80a241.png)

**Comment by lucasccordeiro** [comment]
That's very good!
