### ISSUE TITLE
[command-line] list of properties supported by ESBMC

### ISSUE THREAD

**Issue by lucasccordeiro** [Yiannis128/esbmc-ai#11]
You could list the properties supported by ESBMC:

```
Property checking:
  --no-assertions                  ignore assertions
  --no-bounds-check                do not do array bounds check
  --no-div-by-zero-check           do not do division by zero check
  --no-pointer-check               do not do pointer check
  --no-align-check                 do not check pointer alignment
  --no-pointer-relation-check      do not check pointer relations
  --no-unlimited-scanf-check       do not do overflow check for scanf/fscanf
                                   with unlimited character width.
  --nan-check                      check floating-point for NaN
  --memory-leak-check              enable memory leak check
  --overflow-check                 enable arithmetic over- and underflow check
  --ub-shift-check                 enable undefined behaviour check on shift
                                   operations
  --struct-fields-check            enable over-sized read checks for struct
                                   fields
  --deadlock-check                 enable global and local deadlock check with
                                   mutex
  --data-races-check               enable data races check
  --lock-order-check               enable for lock acquisition ordering check
  --atomicity-check                enable atomicity check at visible
                                   assignments
  --stack-limit bits (=-1)         check if stack limit is respected
  --error-label label              check if label is unreachable
  --force-malloc-success           do not check for malloc/new failure
```

**Comment by Yiannis128** [comment]
Where could I list these? There are a couple of locations:
* `./main.py -h` could print these out.
* I could also include them in the README.md file

Where do you think it's most appropriate?

**Comment by lucasccordeiro** [comment]
> ./main.py -h could print these out.
> I could also include them in the README.md file

Both ;-)

**Comment by lucasccordeiro** [comment]
You could print these options in:

* ./main.py -h 
* inside the chat too

**Comment by Yiannis128** [comment]
OK, I will add it in the `-h`, and also in the `README.md`.

I think the text inside the chat should outline commands that only work when inside the chat, so in the future, if there are ways to interact with ESBMC inside the chat (after the initial parameters are set) then it would be an appropriate place to include them. Do you agree with this logic?

**Comment by Yiannis128** [comment]
> You could print these options in:
> 
>     * ./main.py -h
> 
>     * inside the chat too

So, I've added the ESBMC usage into the `README.md` file, but, after adding the message to the help text, `argparse` is the library I'm using to parse the arguments, and it formats the text completely wrong, so I will need to figure out a solution.

**Comment by Yiannis128** [comment]
I've fixed the issue and made it appear in the `-h` text properly in https://github.com/Yiannis128/esbmc-ai/commit/06a8810190f7f31a6f040d1078d3a40f3b9b3939
