### ISSUE TITLE
Flag argument to not replace ESBMC arguments and instead append them

### ISSUE THREAD

**Issue by Yiannis128** [Yiannis128/esbmc-ai#16]
There should be a flag that can be supplied that will cause all additional ESBMC arguments to be appended to the default ones. This is to avoid needing to type like 10 arguments in order to add to the default ones.

`-a` `--append-args`, perhaps?

**Comment by lucasccordeiro** [comment]
I agree with this suggestion. This solution looks very good to me.

**Comment by Yiannis128** [comment]
Fixed in https://github.com/Yiannis128/esbmc-ai/commit/06a8810190f7f31a6f040d1078d3a40f3b9b3939
