### ISSUE TITLE
[fix-code] Implementation

### ISSUE THREAD

**Issue by Yiannis128** [Yiannis128/esbmc-ai#5]
When the AI model suggests fixes for the code, and you ask it to print out the whole source, the code should automatically be first verified with ESBMC to ensure it is correct. In the case it is wrong, new code will need to be generated.

This is an ideal program loop:
1. User runs the program
2. ESBMC runs
3. AI model scans ESBMC output
4. AI model explains the code and issue
5. User can query the AI model
6. When the user asks for solution
7. AI model generates a solution (will need to somehow make it always show the code as a whole here, currently, it shows the code partially most of the time, and only sometimes as a whole).
8. Detect that the model generated the solution, and pass it to ESBMC.
9. ESBMC outputs feedback
    1. If successful, ask AI model to generate a comment walking through the fixed code (to explain it to the user).
    2. If unsuccessful, ask AI to fix the code (goto step 6).

# Remaining TODO:

I'm not sure if these issues are going to make it in, but they would definitely make the generator mode AI more accurate.

- [x] Basic implementation 
- [ ] **Experimental:** Send to the generator chat the initial explanation (from initial prompt) that the user mode chat generates. This has the potential to guide the AI model to generate correct code.
- [ ] **Experimental:** Add a parameter to the /fix-code command that is a line-string (just a string that takes the whole line after the command) that gives an explanation to the generator AI about what this code does. If the parameter is not specified, then use potentially call the user mode chat to provide one?
- [ ] Add to the `SolutionGenerator` the output of ESBMC after generating a solution for each attempt, this could potentially guide the AI to create a more accurate fix. Issue tracking this: https://github.com/Yiannis128/esbmc-ai/issues/22

**Comment by lucasccordeiro** [comment]
@Yiannis128: This is a good example:

```C
#include <assert.h>
int main() {
    __int128 X;
    __ESBMC_assume(X>0);
    __int128 Z = 2;
    Z = Z << 70;
    assert((X+Z) > 0);
}
```

The corrected version provided by ChatGPT is:

```C
#include <assert.h>
#include <stdint.h>
int main() {
    uint64_t X;
    uint64_t Z = 2;
    Z = Z << 62;
    assert((X+Z) > 0);
}
```

However, this version still fails with ESBMC.

```
Counterexample:

State 1 file shift-correct.c line 7 function main thread 0
----------------------------------------------------
Violated property:
  file shift-correct.c line 7 function main
  assertion (X+Z) > 0
  X + Z > 0


VERIFICATION FAILED
```

**Comment by Yiannis128** [comment]
OK, here is how I think a quick and initial implementation of this could work:

1. ESBMC-AI passes source to ESBMC
2. ESBMC outputs correction
3. ESBMC-AI passes ESBMC output to AI
4. AI gives NL explanation
5. I implement an in-chat command `/generate-solution`
6. This will set the system and initial message for the AI model to show **only** the code, so it will be a differnet mode of functionality.
    1. The AI is tasked with outputting a correction with specific parameter: no Markdown format code only
    2. The AI model output is passed to ESBMC and then ESBMC output is received
    3. The ESBMC output is read and if VERIFICATION SUCCESSFUL
        1. Instruct the AI to explain the code and walk the user through it
        2. Go back to normal chat mode
    4. If the code is not successful, then go to step 6.i and try again.

In the future, we can implement a system where the user can ask the AI with natural language, but that currently needs more research. This would be a quick initial solution as we skip the problem of detecting and determining if the NL input from the user is a specific command that ESBMC-AI needs to intercept and process.

**Comment by Yiannis128** [comment]
I've created a branch to track the implementation of this https://github.com/Yiannis128/esbmc-ai/tree/solution-evaluation-loop

**Comment by Yiannis128** [comment]
Initial implementation complete, will need to see how the UX and also make some adjustments (such as letting the user NL chat know about the solution if one is generated).

**Comment by Yiannis128** [comment]
@lucasccordeiro I've added a TODO list of features that can be implemented to enchance the accuracy of the /fix-code command, let me know what you think!
