### ISSUE TITLE
Initial Setup in Windows OS

### ISSUE THREAD

**Issue by Paulovss85** [Yiannis128/esbmc-ai#74]
Hello. Regarding Initial Setup

Assuming the ESBMC.exe path is _C:\\user\ESBMC\ESBMC-Windows\bin_

The files _config.json_ and _.env_ should in which folder( directory)?
The path above should be added in _config.json_

Could share the folder structure to merge esbmc-ai to esbmc?

**Comment by Yiannis128** [comment]
Hi, the files `config.json` and `.env` should be in the directory where ESBMC-AI is in. So let's say you have ESBMC-AI in a directory: `C:\user\esbmc-ai`, then the file path for both `config.json` and `.env` should be:

* `C:\user\esbmc-ai\config.json`
* `C:\user\esbmc-ai\.env`

I'm working towards making this program available in [PyPi](https://pypi.org/), so you will be able to install it through Pip, but for now, if you require anymore help, please let me know :)

**Comment by Yiannis128** [comment]
I've enabled discussions, please ask me any questions you have still there :)
