### ISSUE TITLE
[readme] update instructions

### ISSUE THREAD

**Issue by lucasccordeiro** [Yiannis128/esbmc-ai#8]
You could replace:

Create a .env file using the provided .env.example as a template, and, insert your OpenAI API key.

with

Create a `.env` file using the provided `.env.example` as a template. After inserting your OpenAI API key, rename this template file to `.env`.

**Comment by Yiannis128** [comment]
I have updated the readme file. Is it a good change? Let me know please.

**Comment by lucasccordeiro** [comment]
The instructions are now much better! Many thanks, @Yiannis128 .

**Comment by lucasccordeiro** [comment]
Overall, it looks good. You could also explain what ESBMC is in the beginning :-)

**Comment by Yiannis128** [comment]
OK I'll add an explanation block quote from the ESBMC GitHub repo.

**Comment by Yiannis128** [comment]
Done, the explanation is added at the beginning:

![image](https://user-images.githubusercontent.com/9535618/235729004-ee347584-307d-41c2-9b52-a82cdcb71dfc.png)
