### ISSUE TITLE
Couldn't run ESBMC-AI

### ISSUE THREAD

**Issue by mihaistate** [Yiannis128/esbmc-ai#91]
I have installed the pre-built version of ESBMC from here: https://github.com/esbmc/esbmc/releases
I have changed the .env file with the OPENAI and HuggingFace keys and updated the ./config.json file with the right esbmc file: "esbmc_path": "/home/csimage/Downloads/linux-release/bin/esbmc"

When I run anothe sample program, the same error occurs.
 
When I run ./esbmc_ai.py samples/hello_world.c, these errors occur:
Traceback (most recent call last):
  File "/home/csimage/comp30030/esbmc-ai/./esbmc_ai.py", line 5, in <module>
    from esbmc_ai_lib.__main__ import main
  File "/home/csimage/comp30030/esbmc-ai/esbmc_ai_lib/__main__.py", line 14, in <module>
    from langchain.base_language import BaseLanguageModel
ModuleNotFoundError: No module named 'langchain'

**Comment by mihaistate** [comment]
pip install langchain solved the issue.

**Comment by Yiannis128** [comment]
Glad you got it fixed!

**Comment by Yiannis128** [comment]
I will update the requirements file to include langchain!

**Comment by mihaistate** [comment]
I also had to install text_generation, openai and dotenv.

**Comment by Yiannis128** [comment]
> I also had to install text_generation, openai and dotenv.

I will be pushing a new release in the upcoming days with the requirements.txt file being up-to-date. I need to implement a GH action in the future to automate it.
